SET ECHO OFF;
SET HEADING OFF;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET TERM OFF;
SET DEFINE OFF;
SPOOL \\servif-home\homes\mguilhin\Bureau\grant.sql

SELECT 'GRANT SELECT ON ' || TABLE_NAME || ' TO MELKARCHOU;' as CMD
FROM USER_TABLES
UNION
SELECT 'GRANT SELECT ON ' || TABLE_NAME || ' TO TVERNY;' as CMD
FROM USER_TABLES;

SPOOL OFF;

SET HEADING ON;
SET FEEDBACK ON;
SET VERIFY ON;
SET TERM ON;
SET DEFINE ON;
SET ECHO ON;