report: clean
	mkdir teo_bouvard_a2
	cp -r bbs.py cipher.py keygen.py README report.pdf demo.sh files teo_bouvard_a2
	cd teo_bouvard_a2 && tar -czf ../teo_bouvard_a2.tar.gz *
	rm -rf teo_bouvard_a2
clean:
	rm -rf teo_bouvard_a2 teo_bouvard_a2.tar.gz